name: TEMMETA
channels:
  - defaults
dependencies:
  - pandas
  - numpy
  - matplotlib
  - scipy
  - pip:
    - jupyter
    - hyperspy
    - matplotlib_scalebar
    - tqdm
    - Pillow
    - opencv-python
    - PyQt5
